spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

---

spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:idol-kingdom
    username: sa
    password:
  h2:
    console:
      enabled: true


server:
  port: 8080