spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:idol-kingdom
    username: sa
    password:
    h2:
      console:
        enabled: true

---

spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:idol-kingdom
    username: sa
    password:
  h2:
    console:
      enabled: true


server:
  port: 8080


---
cloud.aws:
  credentials:
    accessKey: accessKey
    secretKey: secretKey
  region:
    static: ap-northeast-2
  stack:
    auto: false
